#:import theme_manager themes.theme_manager

# Главный файл KV - загружает все экраны
#:include screens/accounts_screen.kv
#:include screens/operations_screen.kv
#:include screens/analytics_screen.kv
#:include screens/more_screen.kv

# Стиль для ScreenManager
ScreenManager:
    canvas.before:
        Color:
            rgba: theme_manager.get_color('background')
        Rectangle:
            pos: self.pos
            size: self.size